cursor #eddeec
cursor_text_color #d0c2cf

foreground            #eddeec
background            #18111a
selection_foreground  #432740
selection_background  #e3badb
url_color             #eeb1ff

color0   #18111a
color1   #ff7287
color2   #7fffa0
color3   #ffdd72
color4   #de99f2
color5   #673376
color6   #eeb1ff
color7   #fbefff
color8   #a299a5
color9   #ff9fad
color10  #a5ffbc
color11  #ffe9a5
color12  #f0bcff
color13  #f3c8ff
color14  #f7dbff
color15  #fdf8ff
