cursor #eddeec
cursor_text_color #d0c2cf

foreground            #eddeec
background            #18111a
selection_foreground  #432740
selection_background  #e3badb
url_color             #eeb1ff

color0   #18111a
color1   #db563e
color2   #6ed67b
color3   #d7db7b
color4   #b75dcf
color5   #b590bf
color6   #eeb1ff
color7   #abb2bf
color8   #5c6370
color9   #e0715f
color10  #86e091
color11  #e4e897
color12  #f7c2ff
color13  #9a60c0
color14  #a260a8
color15  #ffffff