general {
    lock_cmd = dms ipc call lock lock
    unlock_cmd = killall hypridle
    before_sleep_cmd = dms ipc call lock lock
    after_sleep_cmd = killall hypridle
    ignore_dbus_inhibit = false
}

listener {
    # Lock screen after 10 minutes
    timeout = 600
    on-timeout = hyprlock
    on-resume = killall hypridle
}

listener {
    # Sleep after 20 minutes
    timeout = 1200
    on-timeout = systemctl suspend
}
