# Window and layer rules (see docs/user/rules.md)
[[window_rule]]
match.title = "zen-beta"
default_workspace = 1
default_maximize = true

[[window_rule]]
match.title = "vesktop"
default_workspace = 1
default_maximize = true

[[window_rule]]
match.title = "kitty"
default_workspace = 2

[[window_rule]]
match.title = "spotify"
default_workspace = 1
default_maximize = true
