# Window and layer rules (see docs/user/rules.md) ---------------------------
[[window_rule]]
match.title = "^notificationtoasts_.+_desktop"
default_position = { x = 0, y = 0, anchor = "bottom_right" }
default_focused = false
default_pinned = true

[[window_rule]]
match.title = "zen-beta"
default_workspace = 1
default_maximize = true

[[window_rule]]
match.title = "vesktop"
default_workspace = 3
default_maximize = false
default_floating = true

[[window_rule]]
match.title = "spotify"
default_workspace = 3
default_maximize = false
default_floating = true

[[window_rule]]
match.title = "kitty"
default_workspace = 2 
default_maximize = false
