[accessibility]
ui_scale = 1.300000011920929

[audio]
enable_sounds = true

[backdrop]
blur_intensity = 0.099999997764825821
enabled = true
tint_intensity = 0.0

[bar]
order = [ "Top-Bar" ]

    [bar.Top-Bar]
    background_opacity = 0.0
    capsule = true
    capsule_border = "primary"
    capsule_fill = "on_primary"
    capsule_foreground = "on_surface"
    capsule_padding = 4.0
    center = [ "control-center" ]
    end = [ "network", "bluetooth", "volume", "input_volume", "brightness", "battery", "notifications" ]
    margin_edge = 0
    margin_ends = 20
    padding = 0
    panel_overlap = 0
    scale = 1.7500000186264515
    shadow = false
    start = [ "launcher", "date", "workspaces", "tray", "cat", "recorder", "clock" ]
    thickness = 47
    widget_spacing = 5

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "session"

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002" ]

    [desktop_widgets.grid]
    cell_size = 24
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 1088.0
    box_width = 1920.0
    cx = 960.0
    cy = 540.0
    output = "eDP-1"
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background_opacity = 0.0
        bands = 32
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 192.0
    box_width = 576.0
    cx = 944.0
    cy = 984.0
    output = "eDP-1"
    rotation = 0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        hide_when_no_media = true
        shadow = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 0

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 660

[location]
auto_locate = true

[osd]
position = "top_right"

[plugin_settings."noctalia/screen_recorder"]
copy_to_clipboard = true
directory = "/home/greed/videos/Recordings"

[plugins]
enabled = [ "noctalia/bongocat", "noctalia/screen_recorder" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"



[shell]
avatar_path = "/home/greed/dotfiles/Pics/Icons-profile pics/absdark_small.png"
corner_radius_scale = 0.70000001043081284
font_family = "JetBrainsMono Nerd Font"
lang = "en"
niri_overview_type_to_launch_enabled = true
password_style = "random"
polkit_agent = true
screen_time_enabled = false
settings_show_advanced = true
time_format = "{:%-I:%M %p}"

    [shell.mpris]
    blacklist = [ "zen-beta", "reddit", "vesktop" ]

    [shell.panel]
    clipboard_placement = "floating"
    control_center_placement = "floating"
    launcher_placement = "floating"
    open_near_click_session = true
    open_near_click_wallpaper = true
    session_placement = "floating"
    transparency_mode = "glass"
    wallpaper_placement = "floating"

    [shell.screen_corners]
    size = 1

    [shell.screenshot]
    directory = "/home/greed/Pictures/Screenshots"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "s"
    variant = "destructive"

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "l"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "e"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "command"
    command = "systemctl reboot --firmware-setup"
    enabled = true
    label = "UEFI"
    shortcut = "u"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    enabled = false
    shortcut = "3"
    variant = "default"

[theme]
builtin = "Dracula"
mode = "dark"

[wallpaper]
directory = "/home/greed/dotfiles/Pics/Wallpapers"
fill_mode = "fit"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/greed/dotfiles/Pics/Wallpapers"

    [wallpaper.last]
    path = "/home/greed/dotfiles/Pics/Wallpapers"

    [wallpaper.monitors.eDP-1]
    path = "/home/greed/dotfiles/Pics/Wallpapers"

[widget.audio_visualizer]
bands = 30
scale = 1.1500000000000001
show_when_idle = true
width = 91.0

[widget.battery]
display_mode = "graphic"
font_weight = 600

[widget.bluetooth]
show_label = true

[widget.cat]
audio_spectrum = true
input_devices = [ "/dev/input/event1" ]
rave_mode = true
type = "noctalia/bongocat:cat"

[widget.cat_2]
audio_spectrum = true
rave_mode = true
tappy_mode = true
type = "noctalia/bongocat:cat"
use_mpris_filter = true

[widget.clock]
format = "{:%-I:%M %p}"

[widget.control-center]
anchor = true
custom_image = "/run/current-system/sw/share/icons/hicolor/scalable/apps/nix-snowflake-white.svg"

[widget.custom_button_2]
glyph = "storage"
label = "/"
type = "custom_button"

[widget.launcher]
anchor = true

[widget.media]
art_size = 95.0
hide_when_no_media = true
max_length = 187
min_length = 0
scale = 0.85000000000000009
title_scroll = "on_hover"

[widget.notifications]
hide_when_no_unread = true

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.sysmon]
visualization = "graph"
show_value = true

[widget.tray]
hidden = [ "blueman" ]
pinned = [ "vesktop", "steam" ]

[widget.workspaces]
hide_when_empty = true
