{
  pkgs,
  inputs,
  ...
}: {
  home.packages = with pkgs; [
    emacs
    syncthing
    wl-clipboard
    onlyoffice-desktopeditors
    zathura
    w3m
    vlc
    yazi
    catppuccin
    thunderbird
    tor-browser
    gimp
    imagemagick
    localsend
    telegram-desktop
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
    firefox
    wget
    curl
    obsidian
    proton-vpn
    cava
    obs-studio
    protonplus
    opencode
    gpu-screen-recorder
  ];
}
