{
  pkgs,
  inputs,
  ...
}: {
  home.packages = with pkgs; [
    emacs
    syncthing
    wl-clipboard
    cliphist
    libqalculate
    onlyoffice-desktopeditors
    zathura
    w3m
    vlc
    yazi
    catppuccin
    thunderbird
    tor-browser
    gimp
    imagemagick
    localsend
    telegram-desktop
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
    firefox
    wget
    curl
    obsidian
    inputs.zen-notes.packages.${pkgs.system}.zennotes-desktop
    proton-vpn
    cava
    obs-studio
    protonplus
    opencode
  ];
}
